"""Tests for MATLAB-grounded heartbeat calculations."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np

SRC_DIR = Path(__file__).resolve().parents[1] / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from calculations.blood_flow_velocity.signal_analysis.heartbeat import (  # noqa: E402
    MATLAB_PADDING_FACTOR,
    run_heartbeat_analysis,
    spectral_heartbeat_analysis,
)


class SpectralHeartbeatTests(unittest.TestCase):
    def test_matlab_padding_and_harmonic_fit(self) -> None:
        dt_seconds = 0.05
        time = np.arange(200, dtype=np.float32) * dt_seconds
        waveform = (
            1.0
            + np.sin(2.0 * np.pi * 1.0 * time)
            + 0.45 * np.sin(2.0 * np.pi * 2.0 * time)
            + 0.25 * np.sin(2.0 * np.pi * 3.0 * time)
        ).astype(np.float32)

        result = spectral_heartbeat_analysis(
            waveform,
            dt_seconds,
            systole_count=10,
        )

        expected_fft_size = waveform.size * (1 + 2 * MATLAB_PADDING_FACTOR)
        self.assertEqual(result.fft_coefficients.size, expected_fft_size)
        self.assertEqual(result.frequencies_hz.size, expected_fft_size // 2 + 1)
        self.assertAlmostEqual(result.estimated_fundamental_hz, 1.0)
        self.assertAlmostEqual(result.fundamental_hz, 1.0, places=6)
        self.assertAlmostEqual(result.heart_rate_hz, 1.0, places=6)
        self.assertAlmostEqual(result.heart_rate_bpm, 60.0, places=5)
        self.assertAlmostEqual(result.period_seconds, 1.0, places=6)
        np.testing.assert_allclose(
            result.frequencies_hz[result.peak_indexes],
            [1.0, 2.0, 3.0],
            atol=1e-6,
        )

    def test_lowest_prominent_peak_is_the_matlab_fundamental(self) -> None:
        dt_seconds = 0.025
        time = np.arange(400, dtype=np.float32) * dt_seconds
        waveform = (
            0.3 * np.sin(2.0 * np.pi * 1.2 * time)
            + np.sin(2.0 * np.pi * 2.4 * time)
        ).astype(np.float32)

        result = spectral_heartbeat_analysis(
            waveform,
            dt_seconds,
            systole_count=12,
        )

        # Reference values generated by MATLAB R2026a from the current
        # BloodFlowVelocity/SpectralWaveformAnalysis.m (N=2, prominence=10%).
        self.assertAlmostEqual(
            result.fundamental_hz,
            1.2,
            delta=1e-12,
        )
        self.assertAlmostEqual(
            result.heart_rate_hz,
            1.2,
            delta=1e-12,
        )
        self.assertAlmostEqual(
            result.heart_rate_ste_hz,
            0.0,
            delta=1e-12,
        )
        np.testing.assert_allclose(
            result.frequencies_hz[result.peak_indexes],
            [1.2, 2.4],
            atol=1e-7,
        )
        self.assertAlmostEqual(result.period_seconds, 1.0 / result.heart_rate_hz)

    def test_heartbeat_runner_combines_systole_boundaries_and_spectral_rate(self) -> None:
        dt_seconds = 0.01
        time = np.arange(1000, dtype=np.float32) * dt_seconds
        waveform = (10.0 + 2.0 * np.sin(2.0 * np.pi * 1.2 * time)).astype(
            np.float32
        )

        result = run_heartbeat_analysis(
            waveform,
            dt_seconds=dt_seconds,
        )

        self.assertGreater(result.systole.systole_indexes.size, 2)
        self.assertAlmostEqual(result.spectral.heart_rate_hz, 1.2, places=6)


if __name__ == "__main__":
    unittest.main()
