"""Tests for MATLAB-grounded heartbeat calculations."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np

SRC_DIR = Path(__file__).resolve().parents[1] / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from calculations.blood_flow_velocity.signal_analysis.heartbeat import (  # noqa: E402
    MATLAB_PADDING_FACTOR,
    run_heartbeat_analysis,
    spectral_heartbeat_analysis,
)
from calculations.dopplerview_analysis.arterial_waveform_analysis import (  # noqa: E402
    ArterialWaveformAnalysisStep,
    _heartbeat_from_available_vessel,
)
from pipelines.waveform_velocity_core.dopplerview.models import (  # noqa: E402
    DopplerViewStepContext,
)


class SpectralHeartbeatTests(unittest.TestCase):
    def test_missing_artery_uses_vein_for_timing_and_keeps_artery_nan(self) -> None:
        dt_seconds = 0.01
        time = np.arange(1000, dtype=np.float32) * dt_seconds
        vein = (10.0 + 2.0 * np.sin(2.0 * np.pi * 1.2 * time)).astype(
            np.float32
        )
        artery = np.full_like(vein, np.nan)
        ctx = DopplerViewStepContext(
            cache={
                "retinal_artery_velocity_signal": artery,
                "retinal_vein_velocity_signal": vein,
            },
            holodoppler_config={"sampling_freq": 100.0, "batch_stride": 1.0},
            dopplerview_config={"PulseAnalysis": {"LowpassFreqHz": 15.0}},
        )

        ArterialWaveformAnalysisStep().run(ctx)

        self.assertEqual("vein", ctx.cache["beat_detection_source"])
        self.assertGreater(ctx.cache["beat_indices"].size, 2)
        self.assertTrue(
            np.all(np.isnan(ctx.cache["retinal_artery_velocity_signal_filtered"]))
        )
        self.assertTrue(
            np.all(np.isfinite(ctx.cache["retinal_vein_velocity_signal_filtered"]))
        )

    def test_missing_both_vessels_produces_full_record_nan_cycle(self) -> None:
        missing = np.full(32, np.nan, dtype=np.float32)

        heartbeat, source = _heartbeat_from_available_vessel(
            missing,
            missing,
            dt_seconds=0.1,
            lowpass_freq_hz=4.0,
        )

        self.assertEqual("none", source)
        np.testing.assert_array_equal(
            heartbeat.systole.systole_indexes,
            [0, 31],
        )
        self.assertTrue(np.isnan(heartbeat.spectral.heart_rate_hz))

    def test_systole_derivative_is_velocity_per_second(self) -> None:
        dt_seconds = 0.01
        time = np.arange(1000, dtype=np.float32) * dt_seconds
        waveform = (10.0 + time + np.sin(2.0 * np.pi * time)).astype(np.float32)

        result = run_heartbeat_analysis(waveform, dt_seconds=dt_seconds)

        expected = np.gradient(
            result.systole.artery_signal_filtered,
            np.float32(dt_seconds),
        )
        np.testing.assert_allclose(result.systole.derivative_signal, expected)

    def test_matlab_padding_and_harmonic_fit(self) -> None:
        dt_seconds = 0.05
        time = np.arange(200, dtype=np.float32) * dt_seconds
        waveform = (
            1.0
            + np.sin(2.0 * np.pi * 1.0 * time)
            + 0.45 * np.sin(2.0 * np.pi * 2.0 * time)
            + 0.25 * np.sin(2.0 * np.pi * 3.0 * time)
        ).astype(np.float32)

        result = spectral_heartbeat_analysis(
            waveform,
            dt_seconds,
            systole_count=10,
        )

        expected_fft_size = waveform.size * (1 + 2 * MATLAB_PADDING_FACTOR)
        self.assertEqual(result.fft_coefficients.size, expected_fft_size)
        self.assertEqual(result.frequencies_hz.size, expected_fft_size // 2 + 1)
        self.assertAlmostEqual(result.estimated_fundamental_hz, 1.0)
        self.assertAlmostEqual(result.fundamental_hz, 1.0, places=6)
        self.assertAlmostEqual(result.heart_rate_hz, 1.0, places=6)
        self.assertAlmostEqual(result.heart_rate_bpm, 60.0, places=5)
        self.assertAlmostEqual(result.period_seconds, 1.0, places=6)
        np.testing.assert_allclose(
            result.frequencies_hz[result.peak_indexes],
            [1.0, 2.0, 3.0],
            atol=1e-6,
        )

    def test_lowest_prominent_peak_is_the_matlab_fundamental(self) -> None:
        dt_seconds = 0.025
        time = np.arange(400, dtype=np.float32) * dt_seconds
        waveform = (
            0.3 * np.sin(2.0 * np.pi * 1.2 * time)
            + np.sin(2.0 * np.pi * 2.4 * time)
        ).astype(np.float32)

        result = spectral_heartbeat_analysis(
            waveform,
            dt_seconds,
            systole_count=12,
        )

        # Reference values generated by MATLAB R2026a from the current
        # BloodFlowVelocity/SpectralWaveformAnalysis.m (N=2, prominence=10%).
        self.assertAlmostEqual(
            result.fundamental_hz,
            1.2,
            delta=1e-12,
        )
        self.assertAlmostEqual(
            result.heart_rate_hz,
            1.2,
            delta=1e-12,
        )
        self.assertAlmostEqual(
            result.heart_rate_ste_hz,
            0.0,
            delta=1e-12,
        )
        np.testing.assert_allclose(
            result.frequencies_hz[result.peak_indexes],
            [1.2, 2.4],
            atol=1e-7,
        )
        self.assertAlmostEqual(result.period_seconds, 1.0 / result.heart_rate_hz)

    def test_heartbeat_runner_combines_systole_boundaries_and_spectral_rate(self) -> None:
        dt_seconds = 0.01
        time = np.arange(1000, dtype=np.float32) * dt_seconds
        waveform = (10.0 + 2.0 * np.sin(2.0 * np.pi * 1.2 * time)).astype(
            np.float32
        )

        result = run_heartbeat_analysis(
            waveform,
            dt_seconds=dt_seconds,
        )

        self.assertGreater(result.systole.systole_indexes.size, 2)
        self.assertAlmostEqual(result.spectral.heart_rate_hz, 1.2, places=6)


if __name__ == "__main__":
    unittest.main()
