% 1. Clean up previous build folder to avoid conflicts
if isfolder('build')

    try
        rmdir('build', 's');
        fprintf('Removed existing build directory.\n');
    catch ME
        warning('Could not remove build directory. Is a file open?');
    end

end

mkdir('build');

% 2. Convert ONNX models to MAT before compiling
if isfile(fullfile('Tools', 'convertONNXtoMAT.m'))
    run(fullfile('Tools', 'convertONNXtoMAT.m'));
end

% 3. Run Compilation
mcc -m -v launchBatch.m ...
    -o EyeFlowBatch ...
    -d build ...
    -I BloodFlowVelocity ...
    -I CrossSection ...
    -I Loading ...
    -I Parameters ...
    -I Preprocessing ...
    -I Scripts ...
    -I Segmentation ...
    -I SHAnalysis ...
    -I Tools ...
    -I Outputs ...
    -a 'Parameters/DefaultEyeFlowParams.json' ...
    -a 'Parameters/DefaultEyeFlowParamsBatch.json' ...
    -a eyeflow_logo.png ...
    -a version.txt ...
    -a Models/opticdisc.mat ...
    -a Models/iternet5_av_diasys.mat ...
    -a Models/iternet5_vesselness.mat
