"""Display formulas attached to AngioEye waveform-shape outputs."""

LATEX_FORMULAS = {
    "mu_t": r"$\mu_t=\frac{\int_0^T v(t)t\,dt}{\int_0^T v(t)\,dt}$",
    "mu_t_over_T": r"$\mu_t/T$",
    "sigma_t": r"$\sigma_t=\sqrt{\frac{\int_0^T v(t)(t-\mu_t)^2\,dt}{\int_0^T v(t)\,dt}}$",
    "sigma_t_over_T": r"$\sigma_t/T$",
    "gamma_t": r"$\gamma_t=\frac{\int_0^T v(t)(t-\mu_t)^3\,dt}{M_0\sigma_t^3}$",
    "t10_over_T": r"$t_{10}/T$",
    "t25_over_T": r"$t_{25}/T$",
    "t50_over_T": r"$t_{50}/T$",
    "t75_over_T": r"$t_{75}/T$",
    "t90_over_T": r"$t_{90}/T$",
    "Q_t_width": r"$Q_{t,\mathrm{width}}=(t_{75}-t_{25})/T$",
    "Q_t_skew": r"$Q_{t,\mathrm{skew}}=\frac{(t_{90}-t_{50})-(t_{50}-t_{10})}{t_{90}-t_{10}}$",
    "W50_over_T": r"$W_{50}/T$",
    "W80_over_T": r"$W_{80}/T$",
    "RI": r"$\mathrm{RI}=1-v_{\min}/v_{\max}$",
    "PI": r"$\mathrm{PI}=(v_{\max}-v_{\min})/\bar v$",
    "R_VTI": r"$\mathrm{R}_{\mathrm{VTI}}=\frac{d(\alpha T)}{D-d(\alpha T)}$",
    "SF_VTI": r"$\mathrm{SF}_{\mathrm{VTI}}=\frac{d(\alpha T)}{D}$",
    "Delta_DTI": r"$\Delta_{\mathrm{DTI}}=\int_0^1\left[\frac{d(\tau T)}{D}-\tau\right]d\tau$",
    "d10_over_D": r"$d_{10}/D$",
    "d25_over_D": r"$d_{25}/D$",
    "d50_over_D": r"$d_{50}/D$",
    "d75_over_D": r"$d_{75}/D$",
    "d90_over_D": r"$d_{90}/D$",
    "Q_d_width": r"$Q_{d,\mathrm{width}}=(d_{75}-d_{25})/D$",
    "Q_d_skew": r"$Q_{d,\mathrm{skew}}=\frac{(d_{90}-d_{50})-(d_{50}-d_{10})}{d_{90}-d_{10}}$",
    "t_max_over_T": r"$t_{\max}/T$",
    "t_min_over_T": r"$t_{\min}/T$",
    "S_rise": r"$S_{\mathrm{rise}}=\frac{T}{\bar v}\max_t\dot v(t)$",
    "S_fall": r"$S_{\mathrm{fall}}=\frac{T}{\bar v}|\min_t\dot v(t)|$",
    "t_rise_over_T": r"$t_{\mathrm{rise}}/T$",
    "t_fall_over_T": r"$t_{\mathrm{fall}}/T$",
    "v_end_over_vbar": r"$\bar v_{\mathrm{end}}/\bar v$",
    "CF": r"$\mathrm{CF}=v_{\max}/v_{\mathrm{RMS}}$",
    "E_LF_over_E_HF": r"$E_{\mathrm{LF}}/E_{\mathrm{HF}}$",
    "eta_h": r"$\eta_h=1-\frac{\int_0^T (v(t)-v_H(t))^2\,dt}{\int_0^T (v(t)-\bar v)^2\,dt}$",
    "N_eff_over_T": r"$N_{\mathrm{eff}}/T=(T\int_0^T p(t)^2\,dt)^{-1}$",
    "N_t_over_T": r"$N_t/T=\exp[-\int_0^T p(t)\ln(Tp(t))\,dt]$",
    "E_slope": r"$E_{\mathrm{slope}}=\frac{T^3}{M_0^2}\int_0^T \dot v(t)^2\,dt$",
}
