function res_struct = getFitParamsStruct()
    res_struct = struct(...
        "alpha_1",                  NaN,                            ... % Womersley number                              (-)
        "alpha_n",                  NaN,                            ... % Womersley number on harmonic                  (-)
        "harmonic",                 NaN,                            ... % Harmonic number                               (-)
        "Kappa_n",                  NaN,                            ... % Condition fit                                 (-)
        "residual_mag_RMS",         NaN,                            ... % Residual magnitude RMS                        (-)
        "residual_phase_RMS",       NaN,                            ... % Residual phase RMS                            (-)
        "residual_phase_RMS_msk",   NaN,                            ... % Residual phase RMS (masked to reduce noise)   (-)
        "harmonic_SNR_dB",          NaN,                            ... % Signal-to-noise ratio at harmonic n           (dB)
        "fit_exitflag",             NaN,                            ... % Reason the solver stopped (see lsqnonlin)     (-)
        "R0",                       NaN,                            ... % Baseline Vessel Radius                        (m)
        "Rn",                       NaN,                            ... % Radius harmonic (complex ?)                   (m)
        "Cn",                       complex(NaN, NaN),              ... % Drive Wall Gain                               (m/s)
        "Dn",                       complex(NaN, NaN),              ... % Moving Wall Gain                              (m/s)
        "center",                   NaN,                            ... % Center offset fit factor                      (-)
        "width",                    NaN,                            ... % Scale fit factor                              (-)
        "omega_0",                  NaN,                            ... % Fundamental angular frequency                 (rad/s)
        "omega_n",                  NaN,                            ... % N-th harmonic angulat frequency               (rad/s)
        "metrics",                  struct(...
            "RnR0_complex",             complex(NaN, NaN),              ... % PWK ≈ D_n / C_n                   (-)
            "Qn",                       complex(NaN, NaN),              ... % Flow                              (m3/s)
            "Gn",                       complex(NaN, NaN),              ... % Gradient                          (Pa/m)
            "Kn",                       complex(NaN, NaN),              ... % Complex Flow Gain                 (-)
            "tau_n",                    complex(NaN, NaN),              ... % Shear                             (Pa)
            "AnA0",                     complex(NaN, NaN),              ... % Area Puls.                        (-) (m2?)
            "nu_app",                   NaN,                            ... % Viscosity (kinetic)               (m2/s) ? (Pa.s)
            "mu_app",                   NaN,                            ... % Viscosity (dynamic)               (m2/s) ? (Pa.s)
            "H_GQ_n",                   complex(NaN, NaN),              ...
            "H_GQ_n_Geonorm_abs",       NaN,                            ...
            "H_tauQ_n",                 complex(NaN, NaN),              ...
            "H_tauQ_n_Geonorm_abs",     NaN,                            ...
            "H_RQ_n",                   complex(NaN, NaN),              ...
            "H_RQ_n_Geonorm_abs",       NaN,                            ...
            "R_seg_n",                  NaN,                            ...
            "C_seg_n",                  NaN,                            ...
            "P_seg_diss_n",             NaN,                            ...
            "P_seg_store_n",            NaN,                            ...
            "Mean_D1_amp",              NaN,                            ...
            "Ratio_D1_V1",              NaN                             ...
        )                                                           ... 
    );
end