"""Velocity-analysis defaults."""

LEGACY_BAND_LIMITED_SIGNAL_HARMONIC_COUNT = 13
SEGMENT_RING_COUNT = 16
SEGMENT_INNER_RADIUS_FRAC = 0.10
SEGMENT_LENGTH_FRAC = 0.025
CROSS_SECTION_SCALE_FACTOR_WIDTH = 3.0
CROSS_SECTION_HYDRODYNAMIC_DIAMETERS = True
CROSS_SECTION_VELOCITY_PROFILE_THRESHOLD = 0.5
CROSS_SECTION_ROTATE_FROM_MASK = False
REFERENCE_OPTIC_DISC_DIAMETER_MM = 1.91
DEFAULT_PIXEL_SIZE_MM = 0.0191
SPATIAL_INTERPOLATION_FACTOR = 1.0
