"""Velocity-analysis defaults."""

LEGACY_BAND_LIMITED_SIGNAL_HARMONIC_COUNT = 13
# Number of uniformly spaced radii across the longest lateral FOV dimension.
NUMBER_OF_RADII_IN_FOV = 25
SEGMENT_INNER_RADIUS_FRAC = 0.10
SEGMENT_OUTER_RADIUS_FRAC = 0.35
CROSS_SECTION_HYDRODYNAMIC_DIAMETERS = True
CROSS_SECTION_VELOCITY_PROFILE_THRESHOLD = 0.5
CROSS_SECTION_ROTATE_FROM_MASK = False
CROSS_SECTION_SUBMASK_SIZE_PERCENTILE_KEPT = 0.95
REFERENCE_OPTIC_DISC_DIAMETER_MM = 1.91
DEFAULT_PIXEL_SIZE_MM = 0.0191
SPATIAL_INTERPOLATION_FACTOR = 1.0
