"""Legacy defaults for waveform-shape metrics calculations."""

LEGACY_BAND_LIMITED_SIGNAL_HARMONIC_COUNT = 13
DOPPLERVIEW_DEFAULT_LOCAL_BACKGROUND_DIST = 2
LEGACY_FILTER_VELOCITY_SIGNALS = True
LEGACY_VELOCITY_SIGNAL_LOWPASS_HZ = 15.0
LEGACY_SEGMENT_INNER_RADIUS_FRAC = 0.10
LEGACY_SEGMENT_RING_COUNT = 10
